version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}cashmachinewebapp
    build:
      context: .
      dockerfile: CashMachineWebApp/Dockerfile

  client:
    image: client
    build:
      context: ./example-client
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline
